export enum PointOfAttentionType {
  ALL = 'ALL',
  ONLY_ATER_RECEPTION = 'ONLY_ONE_CALL',
  ONLY_RECEPTION = 'ONLY_RECEPTION',
  ONLY_ATTENDED = 'ONLY_ATTENDED',
}

export enum CallPriorityType {
  ONLY_CALL_PRIORITY = 'ONLY_CALL_PRIORITY',
  NO_CALL_PRIORITY = 'NO_PRIORITY',
  MIXED = 'MIXED',
}
